name: Get YouTube Live m3u8
on:
  schedule:
    - cron: '0 0/3 * * *'

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: config
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
    - name: Install yt-dlp
      run: |
        sudo curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp
        sudo chmod a+rx /usr/local/bin/yt-dlp
        # 00無訊號   
    - name: Get 00.m3u8
      run: |
        touch ./00.m3u8
        sudo cat >./00.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=wKjPli-AHdA)
        EOL
        # 01宜蘭-福隆1	
    - name: Get 01.m3u8
      run: |
        touch ./01.m3u8
        sudo cat >./01.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=NeKjZx8aN-w)
        EOL

    - name: Get 104.m3u8
      run: |
        touch ./104.m3u8
        sudo cat >./104.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/@worldtv8904/live)
        EOL
        # 105佛衛慈悲台 xxx
    - name: Get 105.m3u8
      run: |
        touch ./105.m3u8
        sudo cat >./105.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/@user-ii5su6is2r/live)
        EOL
        # 106信大電視台
    - name: Get 106.m3u8
      run: |
        touch ./106.m3u8
        sudo cat >./106.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/@user-su3ej8xu1o/live)
        EOL
        # 108新唐人亞太台
    - name: Get 108.m3u8
      run: |
        touch ./108.m3u8
        sudo cat >./108.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/@NTDAPTV/live)
        EOL
        # 109正德電視台
    - name: Get 109.m3u8
      run: |
        touch ./109.m3u8
        sudo cat >./109.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/@chengteTV/live)
        EOL
        # 110天良綜合台 xxx
    - name: Get 110.m3u8
      run: |
        touch ./110.m3u8
        sudo cat >./110.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/@user-om2fo1rc7p/live)
        EOL
        # 115新天地民俗台
    - name: Get 115.m3u8
      run: |
        touch ./115.m3u8
        sudo cat >./115.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/@user-ju8hx7pn3d/live)
        EOL
        # 116三聖電視台
    - name: Get 116.m3u8
      run: |
        touch ./116.m3u8
        sudo cat >./116.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/@tsimtv-02/live)
        EOL
        # 118天美麗電視台
    - name: Get 118.m3u8
      run: |
        touch ./118.m3u8
        sudo cat >./118.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/@user-su2ml3jf7w/live)
        EOL
        # 119桐瑛電視台
    - name: Get 119.m3u8
      run: |
        touch ./119.m3u8
        sudo cat >./119.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/@user-xh5zh4hi9n/live)
        EOL
        # 120雙子衛視 XXx
    - name: Get 120.m3u8
      run: |
        touch ./120.m3u8
        sudo cat >./120.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/@user-bp6sm2nq9u/live)
        EOL
        # 121viva購物2台
    - name: Get 121.m3u8
      run: |
        touch ./121.m3u8
        sudo cat >./121.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=LEOat38Iuao)
        EOL
        # 123國會頻道1
    - name: Get 123.m3u8
      run: |
        touch ./123.m3u8
        sudo cat >./123.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=4HysYHJ6GkY)
        EOL
        # 124國會頻道2
    - name: Get 124.m3u8
      run: |
        touch ./124.m3u8
        sudo cat >./124.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=RAP4h3q6_Sg)
        EOL
        # 125幸福空間居家台
    - name: Get 125.m3u8
      run: |
        touch ./125.m3u8
        sudo cat >./125.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/@plus8394/live)
        EOL
        # 129東森財經股市
    - name: Get 129.m3u8
      run: |
        touch ./129.m3u8
        sudo cat >./129.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=LbS-xQ67fos)
        EOL
        # 154中視新聞台
    - name: Get 154.m3u8
      run: |
        touch ./154.m3u8
        sudo cat >./154.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=TCnaIE_SAtM)
        EOL
        # 155台視新聞台
    - name: Get 155.m3u8
      run: |
        touch ./155.m3u8
        sudo cat >./155.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=xL0ch83RAK8)
        EOL
        # 159華視新聞資訊
    - name: Get 159.m3u8
      run: |
        touch ./159.m3u8
        sudo cat >./159.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=wM0g8EoUZ_E)
        EOL
        # 222寰宇新聞台
    - name: Get 222.m3u8
      run: |
        touch ./222.m3u8
        sudo cat >./222.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/watch?v=B7Zp3d6xXWw)
        EOL
        # 297大愛二台
    - name: Get 297.m3u8
      run: |
        touch ./297.m3u8
        sudo cat >./297.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/@DaAiVideo/live)
        EOL
        # 950華語流行暢銷
    - name: Get 950.m3u8
      run: |
        touch ./950.m3u8
        sudo cat >./950.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/@2olive153/live)
        EOL
        # 951華語KKBOX新歌
    - name: Get 951.m3u8
      run: |
        touch ./951.m3u8
        sudo cat >./951.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/@kkbox4422/live)
        EOL
    - name: git add
      run: |
        git add -A
        ls -la
    - name: commit & push
      run: |
        git commit -m "links are updated"
        git push
